# Generated by Django 5.1 on 2026-09-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['modified', 'id'], name='idx_film_work_modified_id'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['modified', 'id'], name='idx_genre_modified_id'),
        ),
        migrations.AddIndex(
            model_name='genrefilmwork',
            index=models.Index(fields=['created', 'id'], name='idx_gfw_created_id'),
        ),
        migrations.AddIndex(
            model_name='genrefilmwork',
            index=models.Index(fields=['genre', 'film_work'], name='idx_gfw_genre_id_film_work_id'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['modified', 'id'], name='idx_person_modified_id'),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(fields=['created', 'id'], name='idx_pfw_created_id'),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(fields=['person', 'film_work'], name='idx_pfw_person_id_film_work_id'),
        ),
    ]
